// Standalone dev tool (run with `dart run`, NOT part of the app).
//
// Fuses the three per-pose meshes (frontal / left40 / right40) into one
// `merged.ply` using the region table generated by generate_face_regions.dart.
//
// Because the meshes are index-aligned and share ARKit's fixed topology, the
// merge is a per-vertex pick/blend in local space — no alignment/transform:
//   merged[i] = lerp(frontal[i], sideSource[i], FaceRegions.sideWeight[i])
// where sideSource is the side capture that observed that cheek. The merged
// mesh reuses the frontal triangle faces.
//
// Usage:
//   dart run tool/merge_regions.dart <frontal.ply> <left40.ply> <right40.ply> \
//       [--flip] [--out=<merged.ply>]
//
//   --flip   swap which side capture fills the left vs right regions (use if the
//            coloured region mesh looked mirrored on device).
//
// The left/right PLYs are the two side captures. By default the left region is
// sourced from the FIRST side file, the right region from the SECOND.

import 'dart:io';

import 'package:flutter_face_scan/features/face_capture/domain/constants/face_regions.g.dart';

void main(List<String> args) {
  final List<String> positional = <String>[];
  bool flip = false;
  String? out;
  for (final String arg in args) {
    if (arg == '--flip') {
      flip = true;
    } else if (arg.startsWith('--out=')) {
      out = arg.substring('--out='.length);
    } else if (!arg.startsWith('--')) {
      positional.add(arg);
    }
  }
  if (positional.length < 3) {
    stderr.writeln(
      'Usage: dart run tool/merge_regions.dart '
      '<frontal.ply> <left40.ply> <right40.ply> [--flip] [--out=merged.ply]',
    );
    exit(64);
  }

  final _Ply frontal = _parsePly(File(positional[0]).readAsStringSync());
  final _Ply leftSide = _parsePly(File(positional[1]).readAsStringSync());
  final _Ply rightSide = _parsePly(File(positional[2]).readAsStringSync());

  final int n = frontal.verts.length;
  if (n != leftSide.verts.length || n != rightSide.verts.length) {
    stderr.writeln(
      'Vertex counts differ: frontal=$n left=${leftSide.verts.length} '
      'right=${rightSide.verts.length}',
    );
    exit(65);
  }
  if (n != FaceRegions.vertexCount || FaceRegions.sideWeight.length != n) {
    stderr.writeln(
      'Region table size (${FaceRegions.vertexCount}) does not match the mesh '
      '($n). Re-run generate_face_regions.dart on a matching frontal scan.',
    );
    exit(65);
  }

  final List<_V3> merged = <_V3>[];
  int blended = 0;
  for (int i = 0; i < n; i++) {
    final double w = FaceRegions.sideWeight[i];
    if (w <= 0) {
      merged.add(frontal.verts[i]);
      continue;
    }
    final FaceRegion region = FaceRegions.of(i);
    final bool leftRegion =
        region == FaceRegion.leftOuter || region == FaceRegion.leftBlend;
    final bool useLeftFile = leftRegion != flip;
    final _V3 src = (useLeftFile ? leftSide : rightSide).verts[i];
    merged.add(_lerp(frontal.verts[i], src, w));
    if (w < 1) {
      blended++;
    }
  }

  final String outPath = out ?? _siblingPath(positional[0], 'merged.ply');
  File(outPath).writeAsStringSync(_renderPly(merged, frontal.faces));

  stdout
    ..writeln('Merged $n vertices ($blended in blend bands), '
        '${frontal.faces.length} faces.')
    ..writeln('Wrote $outPath  (open in MeshLab/CloudCompare)');
}

_V3 _lerp(_V3 a, _V3 b, double w) => _V3(
      a.x + (b.x - a.x) * w,
      a.y + (b.y - a.y) * w,
      a.z + (b.z - a.z) * w,
    );

String _siblingPath(String reference, String name) {
  final int slash = reference.lastIndexOf('/');
  return slash >= 0 ? '${reference.substring(0, slash + 1)}$name' : name;
}

String _renderPly(List<_V3> verts, List<List<int>> faces) {
  final StringBuffer b = StringBuffer()
    ..writeln('ply')
    ..writeln('format ascii 1.0')
    ..writeln('comment flutter_face_scan region-merged mesh')
    ..writeln('element vertex ${verts.length}')
    ..writeln('property float x')
    ..writeln('property float y')
    ..writeln('property float z');
  if (faces.isNotEmpty) {
    b
      ..writeln('element face ${faces.length}')
      ..writeln('property list uchar int vertex_indices');
  }
  b.writeln('end_header');
  for (final _V3 v in verts) {
    b.writeln('${v.x} ${v.y} ${v.z}');
  }
  for (final List<int> f in faces) {
    b.writeln('3 ${f[0]} ${f[1]} ${f[2]}');
  }
  return b.toString();
}

_Ply _parsePly(String content) {
  final List<String> lines = content.split('\n');
  int headerEnd = -1;
  int vCount = -1;
  int fCount = 0;
  for (int i = 0; i < lines.length; i++) {
    final String line = lines[i].trim();
    if (line.startsWith('element vertex')) {
      vCount = int.tryParse(line.split(RegExp(r'\s+')).last) ?? -1;
    } else if (line.startsWith('element face')) {
      fCount = int.tryParse(line.split(RegExp(r'\s+')).last) ?? 0;
    }
    if (line == 'end_header') {
      headerEnd = i;
      break;
    }
  }
  if (headerEnd < 0) {
    return const _Ply(<_V3>[], <List<int>>[]);
  }

  final List<String> data = <String>[];
  for (int i = headerEnd + 1; i < lines.length; i++) {
    final String line = lines[i].trim();
    if (line.isNotEmpty) {
      data.add(line);
    }
  }

  final int vTarget = vCount >= 0 ? vCount : data.length;
  final List<_V3> verts = <_V3>[];
  int idx = 0;
  for (; idx < data.length && verts.length < vTarget; idx++) {
    final List<String> parts = data[idx].split(RegExp(r'\s+'));
    if (parts.length < 3) {
      continue;
    }
    final double? x = double.tryParse(parts[0]);
    final double? y = double.tryParse(parts[1]);
    final double? z = double.tryParse(parts[2]);
    if (x != null && y != null && z != null) {
      verts.add(_V3(x, y, z));
    }
  }

  final List<List<int>> faces = <List<int>>[];
  for (; idx < data.length && faces.length < fCount; idx++) {
    final List<String> parts = data[idx].split(RegExp(r'\s+'));
    if (parts.length >= 4 && parts[0] == '3') {
      final int? a = int.tryParse(parts[1]);
      final int? b = int.tryParse(parts[2]);
      final int? c = int.tryParse(parts[3]);
      if (a != null && b != null && c != null) {
        faces.add(<int>[a, b, c]);
      }
    }
  }
  return _Ply(verts, faces);
}

class _V3 {
  const _V3(this.x, this.y, this.z);
  final double x;
  final double y;
  final double z;
}

class _Ply {
  const _Ply(this.verts, this.faces);
  final List<_V3> verts;
  final List<List<int>> faces;
}
